name: python_test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - run: python app.py
      
      - name: Run tests
        run: unittest
      
  deploy:
    if: ${{ github.ref_name == 'production' }}
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
