name: Ci

on:
  push:
    branches:
      - production

jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v3
        
        - name: Run
          run: echo Hello, world!
      
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
        - name: deploy
          run: echo "Hello, world"
