name: Ci

on:
  push:
    branches:
      - production

jobs:
  prod-check:
      runs-on: ubuntu-latest
      environment: production
      steps:
        - name: deploy
          run: echo "devops_mid"
